name: flutter_linkify
publish_to: https://onepub.dev/api/kjbbxpsdav/
description: Turns text URLs and emails into clickable inline links in text for Flutter.
version: 5.1.0
homepage: https://github.com/madmini/flutter_linkify

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.13.8"

dependencies:
  flutter:
    sdk: flutter
  linkify: ^4.0.0

dev_dependencies:
  flutter_lints : ^2.0.0
  test: ^1.16.5
  flutter_test:
    sdk: flutter
